services:
  mc3:
    container_name: minecraft3
    image: itzg/minecraft-server:java21-alpine
    restart: unless-stopped
    ports:
      - "25571:25565/tcp" # minecraft
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      TZ: "America/Moncton"
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_AUTOPAUSE: "true"
      ENABLE_WHITELIST: "true"
      EXISTING_WHITELIST_FILE: "SKIP"
      MAX_TICK_TIME: -1
      SPAWN_PROTECTION: 0
      MAX_MEMORY: "6G"
      VERSION: "1.20.1"
      MOTD: "cobblemon: origins"
      SEED: "penis"
      DIFFICULTY: "normal"
      SNOOPER_ENABLED: "false"
      ALLOW_FLIGHT: "true"
      ENABLE_RCON: "true"
      USE_AIKAR_FLAGS: "true"
      OPS: "IsaacDaybreak"
    volumes:
      - /docker/appdata/minecraft3:/data